package com.example.dominic.androidlessons;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Button;
import android.widget.ImageView;
import android.view.View;

import java.util.*;

//
//public class MainActivity extends AppCompatActivity {
//
//    @Override
//    protected void onCreate(Bundle savedInstanceState) {
//        super.onCreate(savedInstanceState);
//        setContentView(R.layout.activity_main); // R.layout.activity_main
//        // R class contains resource IDs, including layout files, images, widgets as well.
//        // R class is a class generated by android studio as we put in stuff into our app
//        // layout.activity_main contains id for activity_main layout
//        // if we put an image in "drawable", our ID is R.drawable.filename
//
//        // inflating the layout?
//
//    }
//}
public class MainActivity extends AppCompatActivity{

    ArrayList<Integer> images;
    Button charaButton;
    ImageView charaImage;
    int count = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        images = new ArrayList<Integer>();
        images.add(R.drawable.dory);
        images.add(R.drawable.bartsimpson);

        charaImage = findViewById(R.id.charaImages);
        charaButton = findViewById(R.id.charaButton);
        charaButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

            }
        });
    }
}